supabase_url = "https://tatkeyizdrlffrcmbshp.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhdGtleWl6ZHJsZmZyY21ic2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU1MDY2MjMsImV4cCI6MjEwMTA4MjYyM30.m_Z8tt1bvdEPrl0fN7dhaqX16cYA0mM0pFczwnVU1DI"
